name: test

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
        description: Test project
      codecov:
        required: false
        type: boolean
        default: false
        description: Whether to upload code coverage results

jobs:
  test:
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"
      - name: Install dependencies
        run: dotnet restore ${{ inputs.project }}
      - name: Test
        run: >
          dotnet test ${{ inputs.project }} 
          --no-restore 
          --logger "console;verbosity=detailed"
          -p:CollectCoverage=true 
          -p:CoverletOutputFormat="cobertura" 
          -p:CoverletOutput="coverage_report.xml"
          -p:Exclude=\"[*.Test]*,[DragaliaAPI.Test.Utils]*,[DragaliaAPI.Database]DragaliaAPI.Database.Migrations.*,[DragaliaAPI]DragaliaAPI.Models.Generated.*\"
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        if: ${{ inputs.codecov }}
        with:
          files: ${{matrix.project}}/coverage_report.xml
          name: codecov ${{ matrix.project }}
