global using FluentAssertions;
global using Microsoft.AspNetCore.Mvc.Testing;
global using Xunit;
global using Moq;
global using DragaliaAPI.Models;
global using DragaliaAPI.Models.Nintendo;
global using DragaliaAPI.Models.Dragalia;
global using DragaliaAPI.Models.Dragalia.Requests;
global using DragaliaAPI.Models.Dragalia.Responses;