using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json.Linq;

namespace DragaliaAPI.Photon.Plugin.Models.Events
{
    public enum EventCode : byte
    {
        GameEnd = 2,
        Ready = 3,
        NextMap = 4,
        NextEnemyGroup = 5,
        Move = 10,
        AttackHit = 12,
        TransformCharacter = 13,
        TryTransform = 16,
        CharacterState = 17,
        Stamp = 18,
        DungeonObject = 19,
        CharacterData = 20,
        QuestStart = 21,
        TargetParts = 22,
        RoomBroken = 23,
        GameSucceed = 24,
        ForceLeave = 25,
        RebornEvent = 27,
        QuestContinue = 28,
        Charge = 29,
        WillLeave = 30,
        MoveBundle = 31,
        EventD00562 = 32,
        EventE02660 = 33,
        ThrowCarryRequest = 38,
        ThrowCarryReply = 39,
        ThrowRelease = 40,
        Regeneration = 41,
        RequestGuard = 45,
        DenyGuard = 46,
        RequestGuardCounter = 47,
        RequestCounter = 48,
        ChangeAbility = 49,
        ChangeBuff = 50,
        EnemyDead = 51,
        ChangeAbnormalStatus = 52,
        EnterAck = 53,
        LeaveAck = 54,
        ClientAck = 55,
        ServerAck = 56,
        SkillPoint = 57,
        BarrieredHit = 58,
        Statistics = 59,
        EnemyAppear = 60,
        DragonGauge = 61,
        Party = 62,
        ClearQuestRequest = 63,
        ClearQuestResponse = 64,
        ClearTimerEvent = 65,
        SlipDamage = 66,
        FailQuestRequest = 67,
        FailQuestResponse = 68,
        DebugInspectionRequest = 69,
        DebugInspectionResponse = 70,
        EnemyAbility = 71,
        Dead = 72,
        AbilityGauge = 73,
        RecoverySpRequest = 74,
        ResetBuffRequest = 75,
        RecoveryHpRequest = 76,
        CharacterStateExtraSync = 77,
        ElectrifyEvent = 78,
        BindEvent = 79,
        CallMinionEvent = 81,
        AppearEnemyEvent = 82,
        SuccessiveGameTimer = 83,
        FireSpecialBullet = 84,
        EnergyPoint = 85,
        CharacterSpecialState = 86,
        DebuffExtraDamage = 87,
        ReduceSacrificeShieldHp = 88,
        RetryVoteEvent = 89,
        MultiWeakEvent = 90,
        DollEvent = 91,
        BRCreateItemEvent = 92,
        BRGetItemEvent = 93,
        BRInitWorld = 94,
        HostMigration = 95,
        GameStepEvent = 96,
        BRDragonGauge = 97,
        BulletEvent = 98,
        KeepAlive = 99,
        Test = 100,
        DebugBattleSetting = 101,
        InternalServerError = 102,
        DebugRaidSetting = 103,
        DebugCommand = 104,
        WarpEvent = 105,
        BRNotifyEvent = 106,
        BuffFieldEvent = 107,
        Dispel = 108,
        ActionPartsNotifyEvent = 109,
        CharacterCustomPointEvent = 111,
        ApplyAbilityEvent = 112,
        Dodge = 113,
        OverDriveCounter = 114,
        AuraEvent = 115,
        PlayerEvent = 116,
        TransSkill = 117,
        DispBuffCaptionEvent = 118,
        ConsumeUtpToRecoverHpEvent = 119,
        TriggerAbility = 120,
        NevOptionEvent = 121,
        DebugBossHpEvent = 122,
        ApplyOpeningDebuffEvent = 123,
        VesselBombEvent = 124,
        ChangeBuffDuration = 125,
        CuttCommandEvent = 126,
        ReasonRemoveActor = 200,
        BotEvent = 123,
        GameList = 230,
        GameListUpdate = 229,
        QueueState = 228,
        Match = 227,
        AppStats = 226,
        LobbyStats = 224,
        Join = byte.MaxValue,
        Leave = 254,
        PropertiesChanged = 253,
        ErrorInfo = 251,
        CacheSliceChanged = 250
    }
}
