using System.Text.Json.Serialization;
using DragaliaAPI.Shared.Definitions.Enums;
using DragaliaAPI.Shared.Definitions.Enums.Dungeon;
using DragaliaAPI.Shared.Definitions.Enums.EventItemTypes;
using DragaliaAPI.Shared.MasterAsset.Models;
using DragaliaAPI.Shared.MasterAsset.Models.Dmode;
using DragaliaAPI.Shared.MasterAsset.Models.Enemy;
using DragaliaAPI.Shared.MasterAsset.Models.Event;
using DragaliaAPI.Shared.MasterAsset.Models.Login;
using DragaliaAPI.Shared.MasterAsset.Models.ManaCircle;
using DragaliaAPI.Shared.MasterAsset.Models.Missions;
using DragaliaAPI.Shared.MasterAsset.Models.QuestDrops;
using DragaliaAPI.Shared.MasterAsset.Models.QuestRewards;
using DragaliaAPI.Shared.MasterAsset.Models.QuestSchedule;
using DragaliaAPI.Shared.MasterAsset.Models.Shop;
using DragaliaAPI.Shared.MasterAsset.Models.Story;
using DragaliaAPI.Shared.MasterAsset.Models.Trade;
using DragaliaAPI.Shared.MasterAsset.Models.User;
using DragaliaAPI.Shared.MasterAsset.Models.Wall;

namespace DragaliaAPI.Shared.Json;

[JsonSerializable(typeof(RepeatSettingType))]
[JsonSerializable(typeof(BattleRoyalEventItemType))]
[JsonSerializable(typeof(BuildEventItemType))]
[JsonSerializable(typeof(Clb01EventItemType))]
[JsonSerializable(typeof(CollectEventItemType))]
[JsonSerializable(typeof(CombatEventItemType))]
[JsonSerializable(typeof(EarnEventItemType))]
[JsonSerializable(typeof(ExHunterEventItemType))]
[JsonSerializable(typeof(ExRushEventItemType))]
[JsonSerializable(typeof(MazeEventItemType))]
[JsonSerializable(typeof(RaidEventItemType))]
[JsonSerializable(typeof(SimpleEventItemType))]
[JsonSerializable(typeof(AbilityTypes))]
[JsonSerializable(typeof(BannerTypes))]
[JsonSerializable(typeof(BuildupPieceTypes))]
[JsonSerializable(typeof(Charas))]
[JsonSerializable(typeof(CurrencyEntityIds))]
[JsonSerializable(typeof(DmodeDungeonItemState))]
[JsonSerializable(typeof(DmodeDungeonItemType))]
[JsonSerializable(typeof(DmodeEnemyLevelType))]
[JsonSerializable(typeof(DmodePoint))]
[JsonSerializable(typeof(DmodeServitorPassiveType))]
[JsonSerializable(typeof(DropObject))]
[JsonSerializable(typeof(DungeonItem))]
[JsonSerializable(typeof(DungeonState))]
[JsonSerializable(typeof(Emblems))]
[JsonSerializable(typeof(EntityTypes))]
[JsonSerializable(typeof(EventEffectTypes))]
[JsonSerializable(typeof(EventKindType))]
[JsonSerializable(typeof(ExpeditionState))]
[JsonSerializable(typeof(FortBuildStatus))]
[JsonSerializable(typeof(FortEffectTypes))]
[JsonSerializable(typeof(FortPlants))]
[JsonSerializable(typeof(ManaNodeTypes))]
[JsonSerializable(typeof(ManaNodes))]
[JsonSerializable(typeof(MaterialCategory))]
[JsonSerializable(typeof(MaterialRarities))]
[JsonSerializable(typeof(Materials))]
[JsonSerializable(typeof(PayTargetType))]
[JsonSerializable(typeof(PaymentTypes))]
[JsonSerializable(typeof(PlusCountType))]
[JsonSerializable(typeof(PurchaseShopType))]
[JsonSerializable(typeof(QuestBonusReceiveType))]
[JsonSerializable(typeof(QuestCompleteType))]
[JsonSerializable(typeof(QuestEventType))]
[JsonSerializable(typeof(QuestGroupIntervalType))]
[JsonSerializable(typeof(QuestGroupType))]
[JsonSerializable(typeof(QuestPlayModeTypes))]
[JsonSerializable(typeof(QuestResetIntervalType))]
[JsonSerializable(typeof(QuestWallTypes))]
[JsonSerializable(typeof(RewardStatus))]
[JsonSerializable(typeof(QuestTypes))]
[JsonSerializable(typeof(RoomStatuses))]
[JsonSerializable(typeof(StoryState))]
[JsonSerializable(typeof(StoryTypes))]
[JsonSerializable(typeof(SummonCampaignTypes))]
[JsonSerializable(typeof(SummonEffectsSage))]
[JsonSerializable(typeof(SummonEffectsSky))]
[JsonSerializable(typeof(SummonPrizeRanks))]
[JsonSerializable(typeof(SummonTickets))]
[JsonSerializable(typeof(Talismans))]
[JsonSerializable(typeof(Toughness))]
[JsonSerializable(typeof(TradeType))]
[JsonSerializable(typeof(UnitElement))]
[JsonSerializable(typeof(UseItem))]
[JsonSerializable(typeof(UseItemEffect))]
[JsonSerializable(typeof(VariationTypes))]
[JsonSerializable(typeof(WeaponSeries))]
[JsonSerializable(typeof(WeaponTypes))]
[JsonSerializable(typeof(WeaponBodies))]
[JsonSerializable(typeof(AmuletReturnBaseValues))]
[JsonSerializable(typeof(Dragons))]
[JsonSerializable(typeof(AbilityCrests))]
[JsonSerializable(typeof(UnitAvailability))]
[JsonSerializable(typeof(SummonExecTypes))]
[JsonSerializable(typeof(List<DmodeAbilityCrest>))]
[JsonSerializable(typeof(List<DmodeAreaInfo>))]
[JsonSerializable(typeof(List<DmodeCharaLevel>))]
[JsonSerializable(typeof(List<DmodeDungeonArea>))]
[JsonSerializable(typeof(List<DmodeDungeonItemData>))]
[JsonSerializable(typeof(List<DmodeDungeonTheme>))]
[JsonSerializable(typeof(List<DmodeEnemyParam>))]
[JsonSerializable(typeof(List<DmodeEnemyTheme>))]
[JsonSerializable(typeof(List<DmodeExpeditionFloor>))]
[JsonSerializable(typeof(List<DmodeQuestFloor>))]
[JsonSerializable(typeof(List<DmodeServitorPassiveLevel>))]
[JsonSerializable(typeof(List<DmodeStrengthAbility>))]
[JsonSerializable(typeof(List<DmodeStrengthParam>))]
[JsonSerializable(typeof(List<DmodeStrengthSkill>))]
[JsonSerializable(typeof(List<DmodeWeapon>))]
[JsonSerializable(typeof(List<EnemyData>))]
[JsonSerializable(typeof(List<EnemyParam>))]
[JsonSerializable(typeof(List<QuestEnemies>))]
[JsonSerializable(typeof(List<BuildEventReward>))]
[JsonSerializable(typeof(List<CombatEventLocation>))]
[JsonSerializable(typeof(List<CombatEventLocationReward>))]
[JsonSerializable(typeof(List<EventData>))]
[JsonSerializable(typeof(List<EventItem<BattleRoyalEventItemType>>))]
[JsonSerializable(typeof(List<EventItem<BuildEventItemType>>))]
[JsonSerializable(typeof(List<EventItem<BuildEventItemType>>))]
[JsonSerializable(typeof(List<EventItem<Clb01EventItemType>>))]
[JsonSerializable(typeof(List<EventItem<CollectEventItemType>>))]
[JsonSerializable(typeof(List<EventItem<CombatEventItemType>>))]
[JsonSerializable(typeof(List<EventItem<EarnEventItemType>>))]
[JsonSerializable(typeof(List<EventItem<ExHunterEventItemType>>))]
[JsonSerializable(typeof(List<EventItem<ExRushEventItemType>>))]
[JsonSerializable(typeof(List<EventItem<MazeEventItemType>>))]
[JsonSerializable(typeof(List<EventItem<RaidEventItemType>>))]
[JsonSerializable(typeof(List<EventItem<SimpleEventItemType>>))]
[JsonSerializable(typeof(List<EventPassive>))]
[JsonSerializable(typeof(List<EventTradeGroup>))]
[JsonSerializable(typeof(List<IEventReward>))]
[JsonSerializable(typeof(List<QuestScoringEnemy>))]
[JsonSerializable(typeof(List<RaidEventItem>))]
[JsonSerializable(typeof(List<RaidEventReward>))]
[JsonSerializable(typeof(List<LoginBonusData>))]
[JsonSerializable(typeof(List<LoginBonusReward>))]
[JsonSerializable(typeof(List<ManaNode>))]
[JsonSerializable(typeof(List<ManaPieceMaterial>))]
[JsonSerializable(typeof(List<ManaPieceType>))]
[JsonSerializable(typeof(List<CharaLimitBreak>))]
[JsonSerializable(typeof(List<AlbumMission>))]
[JsonSerializable(typeof(List<DailyMission>))]
[JsonSerializable(typeof(List<DrillMission>))]
[JsonSerializable(typeof(List<DrillMissionGroup>))]
[JsonSerializable(typeof(List<IExtendedRewardMission>))]
[JsonSerializable(typeof(List<IMission>))]
[JsonSerializable(typeof(List<MainStoryMission>))]
[JsonSerializable(typeof(List<MainStoryMissionGroup>))]
[JsonSerializable(typeof(List<MainStoryMissionGroupRewards>))]
[JsonSerializable(typeof(List<MemoryEventMission>))]
[JsonSerializable(typeof(List<MissionLockRewardType>))]
[JsonSerializable(typeof(List<MissionProgressionInfo>))]
[JsonSerializable(typeof(List<MissionType>))]
[JsonSerializable(typeof(List<NormalMission>))]
[JsonSerializable(typeof(List<PeriodMission>))]
[JsonSerializable(typeof(List<SpecialMission>))]
[JsonSerializable(typeof(List<SpecialMissionGroup>))]
[JsonSerializable(typeof(List<MissionCompleteType>))]
[JsonSerializable(typeof(List<MissionTransportType>))]
[JsonSerializable(typeof(List<QuestBonusReward>))]
[JsonSerializable(typeof(List<QuestDropInfo>))]
[JsonSerializable(typeof(List<QuestRewardData>))]
[JsonSerializable(typeof(List<QuestScoreMissionData>))]
[JsonSerializable(typeof(List<QuestScoreMissionRewardInfo>))]
[JsonSerializable(typeof(List<QuestScheduleInfo>))]
[JsonSerializable(typeof(List<IShop>))]
[JsonSerializable(typeof(List<MaterialShop>))]
[JsonSerializable(typeof(List<NormalShop>))]
[JsonSerializable(typeof(List<SpecialShop>))]
[JsonSerializable(typeof(List<EventStory>))]
[JsonSerializable(typeof(List<QuestStory>))]
[JsonSerializable(typeof(List<QuestStoryRewardInfo>))]
[JsonSerializable(typeof(List<StoryData>))]
[JsonSerializable(typeof(List<UnitStory>))]
[JsonSerializable(typeof(List<TreasureTrade>))]
[JsonSerializable(typeof(List<UseItemData>))]
[JsonSerializable(typeof(List<UserLevel>))]
[JsonSerializable(typeof(List<QuestWallDetail>))]
[JsonSerializable(typeof(List<QuestWallMonthlyReward>))]
[JsonSerializable(typeof(List<AbilityCrest>))]
[JsonSerializable(typeof(List<AbilityCrestBuildupGroup>))]
[JsonSerializable(typeof(List<AbilityCrestBuildupLevel>))]
[JsonSerializable(typeof(List<AbilityCrestRarity>))]
[JsonSerializable(typeof(List<AbilityCrestTrade>))]
[JsonSerializable(typeof(List<AbilityData>))]
[JsonSerializable(typeof(List<AbilityLimitedGroup>))]
[JsonSerializable(typeof(List<AreaInfo>))]
[JsonSerializable(typeof(List<DragonRarity>))]
[JsonSerializable(typeof(List<ExAbilityData>))]
[JsonSerializable(typeof(List<FortPlantDetail>))]
[JsonSerializable(typeof(List<MaterialData>))]
[JsonSerializable(typeof(List<QuestData>))]
[JsonSerializable(typeof(List<QuestEvent>))]
[JsonSerializable(typeof(List<QuestEventGroup>))]
[JsonSerializable(typeof(List<QuestTreasureData>))]
[JsonSerializable(typeof(List<RankingData>))]
[JsonSerializable(typeof(List<RankingTierReward>))]
[JsonSerializable(typeof(List<SkillData>))]
[JsonSerializable(typeof(List<Stamp>))]
[JsonSerializable(typeof(List<UnionAbility>))]
[JsonSerializable(typeof(List<WeaponBody>))]
[JsonSerializable(typeof(List<WeaponBodyBuildupGroup>))]
[JsonSerializable(typeof(List<WeaponBodyBuildupLevel>))]
[JsonSerializable(typeof(List<WeaponBodyRarity>))]
[JsonSerializable(typeof(List<WeaponPassiveAbility>))]
[JsonSerializable(typeof(List<WeaponSkin>))]
[JsonSerializable(typeof(List<CharaData>))]
[JsonSerializable(typeof(List<DragonData>))]
[JsonSerializable(typeof(List<IUnitData>))]
[JsonSerializable(typeof(Dictionary<int, MissionProgressionInfo>.ValueCollection))]
[JsonSerializable(typeof(Dictionary<int, List<BuildEventReward>>))]
[JsonSerializable(typeof(Dictionary<int, List<RaidEventReward>>))]
public partial class SharedContext : JsonSerializerContext { }
