using System.Text.Json.Serialization;
using DragaliaAPI.Shared.Definitions.Enums;
using DragaliaAPI.Shared.Definitions.Enums.Dungeon;
using DragaliaAPI.Shared.Definitions.Enums.EventItemTypes;
using DragaliaAPI.Shared.MasterAsset.Models;
using DragaliaAPI.Shared.MasterAsset.Models.Dmode;
using DragaliaAPI.Shared.MasterAsset.Models.Enemy;
using DragaliaAPI.Shared.MasterAsset.Models.Event;
using DragaliaAPI.Shared.MasterAsset.Models.Login;
using DragaliaAPI.Shared.MasterAsset.Models.ManaCircle;
using DragaliaAPI.Shared.MasterAsset.Models.Missions;
using DragaliaAPI.Shared.MasterAsset.Models.QuestDrops;
using DragaliaAPI.Shared.MasterAsset.Models.QuestRewards;
using DragaliaAPI.Shared.MasterAsset.Models.QuestSchedule;
using DragaliaAPI.Shared.MasterAsset.Models.Shop;
using DragaliaAPI.Shared.MasterAsset.Models.Story;
using DragaliaAPI.Shared.MasterAsset.Models.Trade;
using DragaliaAPI.Shared.MasterAsset.Models.User;
using DragaliaAPI.Shared.MasterAsset.Models.Wall;

namespace DragaliaAPI.Shared.Json;

[JsonSerializable(typeof(RepeatSettingType))]
[JsonSerializable(typeof(BattleRoyalEventItemType))]
[JsonSerializable(typeof(BuildEventItemType))]
[JsonSerializable(typeof(Clb01EventItemType))]
[JsonSerializable(typeof(CollectEventItemType))]
[JsonSerializable(typeof(CombatEventItemType))]
[JsonSerializable(typeof(EarnEventItemType))]
[JsonSerializable(typeof(ExHunterEventItemType))]
[JsonSerializable(typeof(ExRushEventItemType))]
[JsonSerializable(typeof(MazeEventItemType))]
[JsonSerializable(typeof(RaidEventItemType))]
[JsonSerializable(typeof(SimpleEventItemType))]
[JsonSerializable(typeof(AbilityTypes))]
[JsonSerializable(typeof(BannerTypes))]
[JsonSerializable(typeof(BuildupPieceTypes))]
[JsonSerializable(typeof(Charas))]
[JsonSerializable(typeof(CurrencyEntityIds))]
[JsonSerializable(typeof(DmodeDungeonItemState))]
[JsonSerializable(typeof(DmodeDungeonItemType))]
[JsonSerializable(typeof(DmodeEnemyLevelType))]
[JsonSerializable(typeof(DmodePoint))]
[JsonSerializable(typeof(DmodeServitorPassiveType))]
[JsonSerializable(typeof(DropObject))]
[JsonSerializable(typeof(DungeonItem))]
[JsonSerializable(typeof(DungeonState))]
[JsonSerializable(typeof(Emblems))]
[JsonSerializable(typeof(EntityTypes))]
[JsonSerializable(typeof(EventEffectTypes))]
[JsonSerializable(typeof(EventKindType))]
[JsonSerializable(typeof(ExpeditionState))]
[JsonSerializable(typeof(FortBuildStatus))]
[JsonSerializable(typeof(FortEffectTypes))]
[JsonSerializable(typeof(FortPlants))]
[JsonSerializable(typeof(ManaNodeTypes))]
[JsonSerializable(typeof(ManaNodes))]
[JsonSerializable(typeof(MaterialCategory))]
[JsonSerializable(typeof(MaterialRarities))]
[JsonSerializable(typeof(Materials))]
[JsonSerializable(typeof(PayTargetType))]
[JsonSerializable(typeof(PaymentTypes))]
[JsonSerializable(typeof(PlusCountType))]
[JsonSerializable(typeof(PurchaseShopType))]
[JsonSerializable(typeof(QuestBonusReceiveType))]
[JsonSerializable(typeof(QuestCompleteType))]
[JsonSerializable(typeof(QuestEventType))]
[JsonSerializable(typeof(QuestGroupIntervalType))]
[JsonSerializable(typeof(QuestGroupType))]
[JsonSerializable(typeof(QuestPlayModeTypes))]
[JsonSerializable(typeof(QuestResetIntervalType))]
[JsonSerializable(typeof(QuestWallTypes))]
[JsonSerializable(typeof(RewardStatus))]
[JsonSerializable(typeof(QuestTypes))]
[JsonSerializable(typeof(RoomStatuses))]
[JsonSerializable(typeof(StoryState))]
[JsonSerializable(typeof(StoryTypes))]
[JsonSerializable(typeof(SummonCampaignTypes))]
[JsonSerializable(typeof(SummonEffectsSage))]
[JsonSerializable(typeof(SummonEffectsSky))]
[JsonSerializable(typeof(SummonPrizeRanks))]
[JsonSerializable(typeof(SummonTickets))]
[JsonSerializable(typeof(Talismans))]
[JsonSerializable(typeof(Toughness))]
[JsonSerializable(typeof(TradeType))]
[JsonSerializable(typeof(UnitElement))]
[JsonSerializable(typeof(UseItem))]
[JsonSerializable(typeof(UseItemEffect))]
[JsonSerializable(typeof(VariationTypes))]
[JsonSerializable(typeof(WeaponSeries))]
[JsonSerializable(typeof(WeaponTypes))]
[JsonSerializable(typeof(WeaponBodies))]
[JsonSerializable(typeof(AmuletReturnBaseValues))]
[JsonSerializable(typeof(Dragons))]
[JsonSerializable(typeof(AbilityCrests))]
[JsonSerializable(typeof(UnitAvailability))]
[JsonSerializable(typeof(SummonExecTypes))]
[JsonSerializable(typeof(IReadOnlyCollection<DmodeAbilityCrest>))]
[JsonSerializable(typeof(IReadOnlyCollection<DmodeAreaInfo>))]
[JsonSerializable(typeof(IReadOnlyCollection<DmodeCharaLevel>))]
[JsonSerializable(typeof(IReadOnlyCollection<DmodeDungeonArea>))]
[JsonSerializable(typeof(IReadOnlyCollection<DmodeDungeonItemData>))]
[JsonSerializable(typeof(IReadOnlyCollection<DmodeDungeonTheme>))]
[JsonSerializable(typeof(IReadOnlyCollection<DmodeEnemyParam>))]
[JsonSerializable(typeof(IReadOnlyCollection<DmodeEnemyTheme>))]
[JsonSerializable(typeof(IReadOnlyCollection<DmodeExpeditionFloor>))]
[JsonSerializable(typeof(IReadOnlyCollection<DmodeQuestFloor>))]
[JsonSerializable(typeof(IReadOnlyCollection<DmodeServitorPassiveLevel>))]
[JsonSerializable(typeof(IReadOnlyCollection<DmodeStrengthAbility>))]
[JsonSerializable(typeof(IReadOnlyCollection<DmodeStrengthParam>))]
[JsonSerializable(typeof(IReadOnlyCollection<DmodeStrengthSkill>))]
[JsonSerializable(typeof(IReadOnlyCollection<DmodeWeapon>))]
[JsonSerializable(typeof(IReadOnlyCollection<EnemyData>))]
[JsonSerializable(typeof(IReadOnlyCollection<EnemyParam>))]
[JsonSerializable(typeof(IReadOnlyCollection<QuestEnemies>))]
[JsonSerializable(typeof(IReadOnlyCollection<BuildEventReward>))]
[JsonSerializable(typeof(IReadOnlyCollection<CombatEventLocation>))]
[JsonSerializable(typeof(IReadOnlyCollection<CombatEventLocationReward>))]
[JsonSerializable(typeof(IReadOnlyCollection<EventData>))]
[JsonSerializable(typeof(IReadOnlyCollection<EventItem<BattleRoyalEventItemType>>))]
[JsonSerializable(typeof(IReadOnlyCollection<EventItem<BuildEventItemType>>))]
[JsonSerializable(typeof(IReadOnlyCollection<EventItem<BuildEventItemType>>))]
[JsonSerializable(typeof(IReadOnlyCollection<EventItem<Clb01EventItemType>>))]
[JsonSerializable(typeof(IReadOnlyCollection<EventItem<CollectEventItemType>>))]
[JsonSerializable(typeof(IReadOnlyCollection<EventItem<CombatEventItemType>>))]
[JsonSerializable(typeof(IReadOnlyCollection<EventItem<EarnEventItemType>>))]
[JsonSerializable(typeof(IReadOnlyCollection<EventItem<ExHunterEventItemType>>))]
[JsonSerializable(typeof(IReadOnlyCollection<EventItem<ExRushEventItemType>>))]
[JsonSerializable(typeof(IReadOnlyCollection<EventItem<MazeEventItemType>>))]
[JsonSerializable(typeof(IReadOnlyCollection<EventItem<RaidEventItemType>>))]
[JsonSerializable(typeof(IReadOnlyCollection<EventItem<SimpleEventItemType>>))]
[JsonSerializable(typeof(IReadOnlyCollection<EventPassive>))]
[JsonSerializable(typeof(IReadOnlyCollection<EventTradeGroup>))]
[JsonSerializable(typeof(IReadOnlyCollection<IEventReward>))]
[JsonSerializable(typeof(IReadOnlyCollection<QuestScoringEnemy>))]
[JsonSerializable(typeof(IReadOnlyCollection<RaidEventItem>))]
[JsonSerializable(typeof(IReadOnlyCollection<RaidEventReward>))]
[JsonSerializable(typeof(IReadOnlyCollection<LoginBonusData>))]
[JsonSerializable(typeof(IReadOnlyCollection<LoginBonusReward>))]
[JsonSerializable(typeof(IReadOnlyCollection<ManaNode>))]
[JsonSerializable(typeof(IReadOnlyCollection<ManaPieceMaterial>))]
[JsonSerializable(typeof(IReadOnlyCollection<ManaPieceType>))]
[JsonSerializable(typeof(IReadOnlyCollection<CharaLimitBreak>))]
[JsonSerializable(typeof(IReadOnlyCollection<AlbumMission>))]
[JsonSerializable(typeof(IReadOnlyCollection<DailyMission>))]
[JsonSerializable(typeof(IReadOnlyCollection<DrillMission>))]
[JsonSerializable(typeof(IReadOnlyCollection<DrillMissionGroup>))]
[JsonSerializable(typeof(IReadOnlyCollection<IExtendedRewardMission>))]
[JsonSerializable(typeof(IReadOnlyCollection<IMission>))]
[JsonSerializable(typeof(IReadOnlyCollection<MainStoryMission>))]
[JsonSerializable(typeof(IReadOnlyCollection<MainStoryMissionGroup>))]
[JsonSerializable(typeof(IReadOnlyCollection<MainStoryMissionGroupRewards>))]
[JsonSerializable(typeof(IReadOnlyCollection<MemoryEventMission>))]
[JsonSerializable(typeof(IReadOnlyCollection<MissionLockRewardType>))]
[JsonSerializable(typeof(IReadOnlyCollection<MissionProgressionInfo>))]
[JsonSerializable(typeof(IReadOnlyCollection<MissionType>))]
[JsonSerializable(typeof(IReadOnlyCollection<NormalMission>))]
[JsonSerializable(typeof(IReadOnlyCollection<PeriodMission>))]
[JsonSerializable(typeof(IReadOnlyCollection<SpecialMission>))]
[JsonSerializable(typeof(IReadOnlyCollection<SpecialMissionGroup>))]
[JsonSerializable(typeof(IReadOnlyCollection<MissionCompleteType>))]
[JsonSerializable(typeof(IReadOnlyCollection<MissionTransportType>))]
[JsonSerializable(typeof(IReadOnlyCollection<QuestBonusReward>))]
[JsonSerializable(typeof(IReadOnlyCollection<QuestDropInfo>))]
[JsonSerializable(typeof(IReadOnlyCollection<QuestRewardData>))]
[JsonSerializable(typeof(IReadOnlyCollection<QuestScoreMissionData>))]
[JsonSerializable(typeof(IReadOnlyCollection<QuestScoreMissionRewardInfo>))]
[JsonSerializable(typeof(IReadOnlyCollection<QuestScheduleInfo>))]
[JsonSerializable(typeof(IReadOnlyCollection<IShop>))]
[JsonSerializable(typeof(IReadOnlyCollection<MaterialShop>))]
[JsonSerializable(typeof(IReadOnlyCollection<NormalShop>))]
[JsonSerializable(typeof(IReadOnlyCollection<SpecialShop>))]
[JsonSerializable(typeof(IReadOnlyCollection<EventStory>))]
[JsonSerializable(typeof(IReadOnlyCollection<QuestStory>))]
[JsonSerializable(typeof(IReadOnlyCollection<QuestStoryRewardInfo>))]
[JsonSerializable(typeof(IReadOnlyCollection<StoryData>))]
[JsonSerializable(typeof(IReadOnlyCollection<UnitStory>))]
[JsonSerializable(typeof(IReadOnlyCollection<TreasureTrade>))]
[JsonSerializable(typeof(IReadOnlyCollection<UseItemData>))]
[JsonSerializable(typeof(IReadOnlyCollection<UserLevel>))]
[JsonSerializable(typeof(IReadOnlyCollection<QuestWallDetail>))]
[JsonSerializable(typeof(IReadOnlyCollection<QuestWallMonthlyReward>))]
[JsonSerializable(typeof(IReadOnlyCollection<AbilityCrest>))]
[JsonSerializable(typeof(IReadOnlyCollection<AbilityCrestBuildupGroup>))]
[JsonSerializable(typeof(IReadOnlyCollection<AbilityCrestBuildupLevel>))]
[JsonSerializable(typeof(IReadOnlyCollection<AbilityCrestRarity>))]
[JsonSerializable(typeof(IReadOnlyCollection<AbilityCrestTrade>))]
[JsonSerializable(typeof(IReadOnlyCollection<AbilityData>))]
[JsonSerializable(typeof(IReadOnlyCollection<AbilityLimitedGroup>))]
[JsonSerializable(typeof(IReadOnlyCollection<AreaInfo>))]
[JsonSerializable(typeof(IReadOnlyCollection<DragonRarity>))]
[JsonSerializable(typeof(IReadOnlyCollection<ExAbilityData>))]
[JsonSerializable(typeof(IReadOnlyCollection<FortPlantDetail>))]
[JsonSerializable(typeof(IReadOnlyCollection<MaterialData>))]
[JsonSerializable(typeof(IReadOnlyCollection<QuestData>))]
[JsonSerializable(typeof(IReadOnlyCollection<QuestEvent>))]
[JsonSerializable(typeof(IReadOnlyCollection<QuestEventGroup>))]
[JsonSerializable(typeof(IReadOnlyCollection<QuestTreasureData>))]
[JsonSerializable(typeof(IReadOnlyCollection<RankingData>))]
[JsonSerializable(typeof(IReadOnlyCollection<RankingTierReward>))]
[JsonSerializable(typeof(IReadOnlyCollection<SkillData>))]
[JsonSerializable(typeof(IReadOnlyCollection<Stamp>))]
[JsonSerializable(typeof(IReadOnlyCollection<UnionAbility>))]
[JsonSerializable(typeof(IReadOnlyCollection<WeaponBody>))]
[JsonSerializable(typeof(IReadOnlyCollection<WeaponBodyBuildupGroup>))]
[JsonSerializable(typeof(IReadOnlyCollection<WeaponBodyBuildupLevel>))]
[JsonSerializable(typeof(IReadOnlyCollection<WeaponBodyRarity>))]
[JsonSerializable(typeof(IReadOnlyCollection<WeaponPassiveAbility>))]
[JsonSerializable(typeof(IReadOnlyCollection<WeaponSkin>))]
[JsonSerializable(typeof(IReadOnlyCollection<CharaData>))]
[JsonSerializable(typeof(IReadOnlyCollection<DragonData>))]
[JsonSerializable(typeof(IReadOnlyCollection<IUnitData>))]
[JsonSerializable(typeof(Dictionary<int, MissionProgressionInfo>.ValueCollection))]
public partial class SharedContext : JsonSerializerContext { }
