version: "3.4"

volumes:
  pgdata:

services:
  dragaliaapi:
    image: dragaliaapi
    container_name: dragaliaapi
    hostname: dragaliaapi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PostgresOptions__Username=$POSTGRES_USER
      - PostgresOptions__Password=$POSTGRES_PASSWORD
      - PostgresOptions__Database=$POSTGRES_DB
    ports:
      - "80:8080"
      - "5000:8080"
    links:
      - postgres
    env_file:
      - .env

  postgres:
    hostname: postgres
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    hostname: redis
    image: redis/redis:7.2.5
    ports:
      - "6379:6379"
