// <auto-generated />
using DragaliaAPI.Models.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DragaliaAPI.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20220928204656_Alpha")]
    partial class Alpha
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.HasSequence("Viewer_id", "dbo")
                .StartsAt(10000000000L);

            modelBuilder.Entity("DragaliaAPI.Models.Database.DbDeviceAccount", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeviceAccounts");
                });

            modelBuilder.Entity("DragaliaAPI.Models.Database.DbSavefilePlayerInfo", b =>
                {
                    b.Property<string>("DeviceAccountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("ViewerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("NEXT VALUE FOR dbo.Viewer_id");

                    b.HasKey("DeviceAccountId");

                    b.ToTable("PlayerSavefiles");
                });
#pragma warning restore 612, 618
        }
    }
}
