// <auto-generated />
using DragaliaAPI.Models.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DragaliaAPI.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20221007002049_SteelGram_1")]
    partial class SteelGram_1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.HasSequence("Viewer_id", "dbo")
                .StartsAt(10000000000L);

            modelBuilder.Entity("DragaliaAPI.Models.Database.DbDeviceAccount", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeviceAccounts");

                    b.HasData(
                        new
                        {
                            Id = "id",
                            HashedPassword = "NMvdakTznEF6khwWcz17i6GTnDA="
                        });
                });

            modelBuilder.Entity("DragaliaAPI.Models.Database.Savefile.DbPlayerCharaData", b =>
                {
                    b.Property<string>("DeviceAccountId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("DEVICE_ACCOUNT_ID");

                    b.Property<int>("CharaId")
                        .HasColumnType("int")
                        .HasColumnName("CHARA_ID");

                    b.Property<byte>("AdditionalMaxLevel")
                        .HasColumnType("tinyint")
                        .HasColumnName("ADD_MAX_LVL");

                    b.Property<int>("Attack")
                        .HasColumnType("int")
                        .HasColumnName("ATK");

                    b.Property<byte>("AttackPlusCount")
                        .HasColumnType("tinyint")
                        .HasColumnName("ATK_PLUS_CNT");

                    b.Property<byte>("BurstAttackLevel")
                        .HasColumnType("tinyint")
                        .HasColumnName("BRST_ATK_LVL");

                    b.Property<long>("ComboBuildupCount")
                        .HasColumnType("bigint")
                        .HasColumnName("COMBO_BUILDUP_CNT");

                    b.Property<long>("Exp")
                        .HasColumnType("bigint")
                        .HasColumnName("EXP");

                    b.Property<byte>("FirstAbilityLevel")
                        .HasColumnType("tinyint")
                        .HasColumnName("ABIL_1_LVL");

                    b.Property<byte>("FirstExAbilityLevel")
                        .HasColumnType("tinyint")
                        .HasColumnName("EX_ABIL_LVL");

                    b.Property<byte>("FirstSkillLevel")
                        .HasColumnType("tinyint")
                        .HasColumnName("SKILL_1_LVL");

                    b.Property<bool>("GetTime")
                        .HasColumnType("bit")
                        .HasColumnName("GET_TIME");

                    b.Property<int>("Hp")
                        .HasColumnType("int")
                        .HasColumnName("HP");

                    b.Property<byte>("HpPlusCount")
                        .HasColumnType("tinyint")
                        .HasColumnName("HP_PLUS_CNT");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit")
                        .HasColumnName("IS_NEW");

                    b.Property<bool>("IsTemporary")
                        .HasColumnType("bit")
                        .HasColumnName("IS_TEMP");

                    b.Property<bool>("IsUnlockEditSkill")
                        .HasColumnType("bit")
                        .HasColumnName("IS_UNLOCK_EDIT_SKILL");

                    b.Property<byte>("Level")
                        .HasColumnType("tinyint")
                        .HasColumnName("LEVEL");

                    b.Property<byte>("LimitBreakCount")
                        .HasColumnType("tinyint")
                        .HasColumnName("LIMIT_BREAK_CNT");

                    b.Property<bool>("ListViewFlag")
                        .HasColumnType("bit")
                        .HasColumnName("LIST_VIEW_FLAG");

                    b.Property<int>("ManaNodeUnlockCount")
                        .HasColumnType("int")
                        .HasColumnName("MANA_NODE_UNLOCK_CNT");

                    b.Property<byte>("Rarity")
                        .HasColumnType("tinyint")
                        .HasColumnName("RARITY");

                    b.Property<byte>("SecondAbilityLevel")
                        .HasColumnType("tinyint")
                        .HasColumnName("ABIL_2_LVL");

                    b.Property<byte>("SecondExAbilityLevel")
                        .HasColumnType("tinyint")
                        .HasColumnName("EX_ABIL_2_LVL");

                    b.Property<byte>("SecondSkillLevel")
                        .HasColumnType("tinyint")
                        .HasColumnName("SKILL_2_LVL");

                    b.Property<byte>("ThirdAbilityLevel")
                        .HasColumnType("tinyint")
                        .HasColumnName("ABIL_3_LVL");

                    b.HasKey("DeviceAccountId", "CharaId");

                    b.ToTable("PlayerUnitData");
                });

            modelBuilder.Entity("DragaliaAPI.Models.Database.Savefile.DbPlayerDragonData", b =>
                {
                    b.Property<string>("DeviceAccountId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("DEVICE_ACCOUNT_ID");

                    b.Property<long>("DragonKeyId")
                        .HasColumnType("bigint")
                        .HasColumnName("DRAGON_KEY_ID");

                    b.Property<byte>("AttackPlusCount")
                        .HasColumnType("tinyint")
                        .HasColumnName("ATK_PLUS_CNT");

                    b.Property<int>("DragonId")
                        .HasColumnType("int")
                        .HasColumnName("DRAGON_ID");

                    b.Property<long>("Exp")
                        .HasColumnType("bigint")
                        .HasColumnName("EXP");

                    b.Property<byte>("FirstAbilityLevel")
                        .HasColumnType("tinyint")
                        .HasColumnName("ABIL_1_LVL");

                    b.Property<byte>("FirstSkillLevel")
                        .HasColumnType("tinyint")
                        .HasColumnName("SKILL_1_LVL");

                    b.Property<bool>("GetTime")
                        .HasColumnType("bit")
                        .HasColumnName("GET_TIME");

                    b.Property<byte>("HpPlusCount")
                        .HasColumnType("tinyint")
                        .HasColumnName("HP_PLUS_CNT");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit")
                        .HasColumnName("IS_LOCKED");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit")
                        .HasColumnName("IS_NEW");

                    b.Property<byte>("Level")
                        .HasColumnType("tinyint")
                        .HasColumnName("LEVEL");

                    b.Property<byte>("LimitBreakCount")
                        .HasColumnType("tinyint")
                        .HasColumnName("LIMIT_BREAK_CNT");

                    b.Property<byte>("SecondAbilityLevel")
                        .HasColumnType("tinyint")
                        .HasColumnName("ABIL_2_LVL");

                    b.HasKey("DeviceAccountId", "DragonKeyId");

                    b.ToTable("PlayerDragonData");
                });

            modelBuilder.Entity("DragaliaAPI.Models.Database.Savefile.DbPlayerDragonReliability", b =>
                {
                    b.Property<string>("DeviceAccountId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("DEVICE_ACCOUNT_ID");

                    b.Property<long>("DragonId")
                        .HasColumnType("bigint")
                        .HasColumnName("DRAGON_ID");

                    b.Property<long>("LastContactTime")
                        .HasColumnType("bigint")
                        .HasColumnName("LAST_CONTACT_TIME");

                    b.Property<long>("ReliabilityExp")
                        .HasColumnType("bigint")
                        .HasColumnName("REL_EXP");

                    b.Property<long>("ReliabilityTotalExp")
                        .HasColumnType("bigint")
                        .HasColumnName("REL_TOTAL_EXP");

                    b.HasKey("DeviceAccountId", "DragonId");

                    b.ToTable("PlayerDragonReliability");
                });

            modelBuilder.Entity("DragaliaAPI.Models.Database.Savefile.DbPlayerUnitStory", b =>
                {
                    b.Property<string>("DeviceAccountId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("DEVICE_ACCOUNT_ID");

                    b.Property<byte>("EntityType")
                        .HasColumnType("tinyint")
                        .HasColumnName("ENTITY_TYPE");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("ENTITY_ID");

                    b.Property<long>("StoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("STORY_ID");

                    b.Property<bool>("DragonId")
                        .HasColumnType("bit")
                        .HasColumnName("DRAGON_ID");

                    b.HasKey("DeviceAccountId", "EntityType", "EntityId", "StoryId");

                    b.ToTable("PlayerUnitStory");
                });

            modelBuilder.Entity("DragaliaAPI.Models.Database.Savefile.DbSavefileUserData", b =>
                {
                    b.Property<string>("DeviceAccountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ActiveMemoryEventId")
                        .HasColumnType("int");

                    b.Property<int>("BuildTimePoint")
                        .HasColumnType("int");

                    b.Property<int>("Coin")
                        .HasColumnType("int");

                    b.Property<int>("CreateTime")
                        .HasColumnType("int");

                    b.Property<int>("Crystal")
                        .HasColumnType("int");

                    b.Property<int>("DewPoint")
                        .HasColumnType("int");

                    b.Property<int>("EmblemId")
                        .HasColumnType("int");

                    b.Property<int>("Exp")
                        .HasColumnType("int");

                    b.Property<int>("FortOpenTime")
                        .HasColumnType("int");

                    b.Property<int>("IsOptin")
                        .HasColumnType("int");

                    b.Property<int>("LastLoginTime")
                        .HasColumnType("int");

                    b.Property<int>("LastStaminaMultiUpdateTime")
                        .HasColumnType("int");

                    b.Property<int>("LastStaminaSingleUpdateTime")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("MainPartyNo")
                        .HasColumnType("int");

                    b.Property<int>("ManaPoint")
                        .HasColumnType("int");

                    b.Property<int>("MaxAmuletQuantity")
                        .HasColumnType("int");

                    b.Property<int>("MaxDragonQuantity")
                        .HasColumnType("int");

                    b.Property<int>("MaxWeaponQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrologueEndTime")
                        .HasColumnType("int");

                    b.Property<int>("QuestSkipPoint")
                        .HasColumnType("int");

                    b.Property<int>("StaminaMulti")
                        .HasColumnType("int");

                    b.Property<int>("StaminaMultiSurplusSecond")
                        .HasColumnType("int");

                    b.Property<int>("StaminaSingle")
                        .HasColumnType("int");

                    b.Property<int>("StaminaSingleSurplusSecond")
                        .HasColumnType("int");

                    b.Property<int>("TutorialFlag")
                        .HasColumnType("int");

                    b.Property<int>("TutorialStatus")
                        .HasColumnType("int");

                    b.Property<long>("ViewerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("NEXT VALUE FOR dbo.Viewer_id");

                    b.HasKey("DeviceAccountId");

                    b.ToTable("SavefileUserData");

                    b.HasData(
                        new
                        {
                            DeviceAccountId = "id",
                            ActiveMemoryEventId = 0,
                            BuildTimePoint = 0,
                            Coin = 0,
                            CreateTime = 1665102049,
                            Crystal = 0,
                            DewPoint = 0,
                            EmblemId = 40000001,
                            Exp = 0,
                            FortOpenTime = 0,
                            IsOptin = 0,
                            LastLoginTime = 0,
                            LastStaminaMultiUpdateTime = 0,
                            LastStaminaSingleUpdateTime = 0,
                            Level = 1,
                            MainPartyNo = 1,
                            ManaPoint = 0,
                            MaxAmuletQuantity = 0,
                            MaxDragonQuantity = 160,
                            MaxWeaponQuantity = 0,
                            Name = "Euden",
                            PrologueEndTime = 0,
                            QuestSkipPoint = 0,
                            StaminaMulti = 12,
                            StaminaMultiSurplusSecond = 0,
                            StaminaSingle = 18,
                            StaminaSingleSurplusSecond = 0,
                            TutorialFlag = 0,
                            TutorialStatus = 0,
                            ViewerId = 0L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
