//HintName: GenerateMasterAssetAttribute.g.cs
// <auto-generated/>

#nullable enable

namespace DragaliaAPI.Shared.MasterAsset;

[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
public sealed class GenerateMasterAssetAttribute<TItem> : System.Attribute
    where TItem : class
{
    public GenerateMasterAssetAttribute(string filepath)
    {
        this.Filepath = filepath;
    }

    public string Filepath { get; }
    
    public string Key { get; set; } = "Id";

    public bool Group { get; set; }
}

[global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = true, Inherited = false)]
public sealed class ExtendMasterAssetAttribute : System.Attribute
{
    public ExtendMasterAssetAttribute(string masterAssetName, string filepath)
    {
        this.MasterAssetName = masterAssetName;
        this.Filepath = filepath;
    }
    
    public string MasterAssetName { get; }
    
    public string Filepath { get; }
    
    public string? FeatureFlag { get; set; }
}