//HintName: MasterAsset.g.cs
// <auto-generated/>

#nullable enable

namespace DragaliaAPI.Shared.MasterAsset;

public static partial class MasterAsset
{
    private const string ErrorUninitialized = "Property access failed: MasterAsset is not yet initialized. Call LoadAsync before accessing any properties.";
    
    private static bool loaded;

    private static global::DragaliaAPI.Shared.MasterAsset.MasterAssetData<global::DragaliaAPI.Shared.MasterAsset.Charas, global::DragaliaAPI.Shared.MasterAsset.CharaData>? charaData;
    public static global::DragaliaAPI.Shared.MasterAsset.MasterAssetData<global::DragaliaAPI.Shared.MasterAsset.Charas, global::DragaliaAPI.Shared.MasterAsset.CharaData> CharaData => charaData ?? throw new InvalidOperationException(ErrorUninitialized);

    private static global::DragaliaAPI.Shared.MasterAsset.MasterAssetData<int, global::DragaliaAPI.Shared.MasterAsset.RankingData>? rankingData;
    public static global::DragaliaAPI.Shared.MasterAsset.MasterAssetData<int, global::DragaliaAPI.Shared.MasterAsset.RankingData> RankingData => rankingData ?? throw new InvalidOperationException(ErrorUninitialized);

    private static global::DragaliaAPI.Shared.MasterAsset.MasterAssetGroup<int, int, global::DragaliaAPI.Shared.MasterAsset.BuildEventReward>? buildEventReward;
    public static global::DragaliaAPI.Shared.MasterAsset.MasterAssetGroup<int, int, global::DragaliaAPI.Shared.MasterAsset.BuildEventReward> BuildEventReward => buildEventReward ?? throw new InvalidOperationException(ErrorUninitialized);

    private static global::DragaliaAPI.Shared.MasterAsset.MasterAssetData<int, global::DragaliaAPI.Shared.MasterAsset.EventData>? eventData;
    public static global::DragaliaAPI.Shared.MasterAsset.MasterAssetData<int, global::DragaliaAPI.Shared.MasterAsset.EventData> EventData => eventData ?? throw new InvalidOperationException(ErrorUninitialized);

    private static global::DragaliaAPI.Shared.MasterAsset.MasterAssetData<int, global::DragaliaAPI.Shared.MasterAsset.DragonData>? dragonData;
    public static global::DragaliaAPI.Shared.MasterAsset.MasterAssetData<int, global::DragaliaAPI.Shared.MasterAsset.DragonData> DragonData => dragonData ?? throw new InvalidOperationException(ErrorUninitialized);
    public static async Task LoadAsync(global::Microsoft.FeatureManagement.IFeatureManager featureManager)
    {
        if (loaded)
        {
            return;
        }
        
        global::System.Threading.Tasks.ValueTask<global::DragaliaAPI.Shared.MasterAsset.MasterAssetData<global::DragaliaAPI.Shared.MasterAsset.Charas, global::DragaliaAPI.Shared.MasterAsset.CharaData>> charaDataTask =
            global::DragaliaAPI.Shared.MasterAsset.MasterAssetData.LoadAsync<global::DragaliaAPI.Shared.MasterAsset.Charas, global::DragaliaAPI.Shared.MasterAsset.CharaData>(
                "CharaData.msgpack",
                (global::DragaliaAPI.Shared.MasterAsset.CharaData x) => x.Id,
                null
            );
        
        global::System.Threading.Tasks.ValueTask<global::DragaliaAPI.Shared.MasterAsset.MasterAssetData<int, global::DragaliaAPI.Shared.MasterAsset.RankingData>> rankingDataTask =
            global::DragaliaAPI.Shared.MasterAsset.MasterAssetData.LoadAsync<int, global::DragaliaAPI.Shared.MasterAsset.RankingData>(
                "TimeAttack/RankingData.msgpack",
                (global::DragaliaAPI.Shared.MasterAsset.RankingData x) => x.QuestId,
                null
            );
        
        global::System.Threading.Tasks.ValueTask<global::DragaliaAPI.Shared.MasterAsset.MasterAssetGroup<int, int, global::DragaliaAPI.Shared.MasterAsset.BuildEventReward>> buildEventRewardTask =
            global::DragaliaAPI.Shared.MasterAsset.MasterAssetGroup.LoadAsync<int, int, global::DragaliaAPI.Shared.MasterAsset.BuildEventReward>(
                "Event/BuildEventReward.msgpack",
                (global::DragaliaAPI.Shared.MasterAsset.BuildEventReward x) => x.Id
            );
        
        global::System.Threading.Tasks.ValueTask<global::DragaliaAPI.Shared.MasterAsset.MasterAssetData<int, global::DragaliaAPI.Shared.MasterAsset.EventData>> eventDataTask =
            global::DragaliaAPI.Shared.MasterAsset.MasterAssetData.LoadAsync<int, global::DragaliaAPI.Shared.MasterAsset.EventData>(
                "Event/EventData.msgpack",
                (global::DragaliaAPI.Shared.MasterAsset.EventData x) => x.Id,
                await LoadEventDataExtension(featureManager)
            );
        
        global::System.Threading.Tasks.ValueTask<global::DragaliaAPI.Shared.MasterAsset.MasterAssetData<int, global::DragaliaAPI.Shared.MasterAsset.DragonData>> dragonDataTask =
            global::DragaliaAPI.Shared.MasterAsset.MasterAssetData.LoadAsync<int, global::DragaliaAPI.Shared.MasterAsset.DragonData>(
                "DragonData.msgpack",
                (global::DragaliaAPI.Shared.MasterAsset.DragonData x) => x.Id,
                await LoadDragonDataExtension(featureManager)
            );

        charaData = await charaDataTask;
        rankingData = await rankingDataTask;
        buildEventReward = await buildEventRewardTask;
        eventData = await eventDataTask;
        dragonData = await dragonDataTask;
        loaded = true;
    }
}
