name: publish

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
        description: ref to checkout
      image-tag:
        required: true
        type: string
        description: Docker image tag

env:
  HUSKY: 0

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '7.0.x' ]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: DragaliaAPI/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dragalia-api:${{ inputs.image-tag }}
