name: Test MaintenanceWorker

on:
  pull_request:
    branches:
      - main
    paths:
      - MaintenanceWorker/**

jobs:
  vitest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: MaintenanceWorker

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: |
          cd MaintenanceWorker
          pnpm install

      - name: Run tests
        run: pnpm run test
